name: 'Manage support request issues'

on:
  issues:
    types: [labeled, unlabeled, reopened]

jobs:
  support:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/support-requests@v5
        with:
          github-token: ${{ github.token }}
          support-label:  "Support request"
          issue-comment: >
            Hi, we only accept **bug reports** on this issue tracker, but this issue looks like a support request.


            Instead of creating an issue, try the following:

            - Check the upstream [PocketMine-MP documentation](https://doc.pmmp.io) for general PocketMine-MP usage questions

            - If this is specific to the NhanAZ fork, open a focused bug report with reproduction steps

          close-issue: true
          lock-issue: false
